// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// cva
List cva(NumericMatrix gamma_initial, NumericVector vy_in, NumericMatrix mX_in, const int K, const double lambda, std::string prior, const bool bUnique);
RcppExport SEXP _blma_cva(SEXP gamma_initialSEXP, SEXP vy_inSEXP, SEXP mX_inSEXP, SEXP KSEXP, SEXP lambdaSEXP, SEXP priorSEXP, SEXP bUniqueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type gamma_initial(gamma_initialSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vy_in(vy_inSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mX_in(mX_inSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< std::string >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< const bool >::type bUnique(bUniqueSEXP);
    rcpp_result_gen = Rcpp::wrap(cva(gamma_initial, vy_in, mX_in, K, lambda, prior, bUnique));
    return rcpp_result_gen;
END_RCPP
}
// blma
List blma(NumericVector vy, NumericMatrix mX, std::string prior, int intercept_col, bool bNatural_Order, bool bIntercept, bool bCentre, int cores);
RcppExport SEXP _blma_blma(SEXP vySEXP, SEXP mXSEXP, SEXP priorSEXP, SEXP intercept_colSEXP, SEXP bNatural_OrderSEXP, SEXP bInterceptSEXP, SEXP bCentreSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vy(vySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< std::string >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< int >::type intercept_col(intercept_colSEXP);
    Rcpp::traits::input_parameter< bool >::type bNatural_Order(bNatural_OrderSEXP);
    Rcpp::traits::input_parameter< bool >::type bIntercept(bInterceptSEXP);
    Rcpp::traits::input_parameter< bool >::type bCentre(bCentreSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(blma(vy, mX, prior, intercept_col, bNatural_Order, bIntercept, bCentre, cores));
    return rcpp_result_gen;
END_RCPP
}
// blma_fixed
List blma_fixed(NumericVector vy, NumericMatrix mX, NumericMatrix mZ, std::string prior, int intercept_col, bool bNatural_Order, bool bIntercept, bool bCentre, int cores);
RcppExport SEXP _blma_blma_fixed(SEXP vySEXP, SEXP mXSEXP, SEXP mZSEXP, SEXP priorSEXP, SEXP intercept_colSEXP, SEXP bNatural_OrderSEXP, SEXP bInterceptSEXP, SEXP bCentreSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vy(vySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mZ(mZSEXP);
    Rcpp::traits::input_parameter< std::string >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< int >::type intercept_col(intercept_colSEXP);
    Rcpp::traits::input_parameter< bool >::type bNatural_Order(bNatural_OrderSEXP);
    Rcpp::traits::input_parameter< bool >::type bIntercept(bInterceptSEXP);
    Rcpp::traits::input_parameter< bool >::type bCentre(bCentreSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(blma_fixed(vy, mX, mZ, prior, intercept_col, bNatural_Order, bIntercept, bCentre, cores));
    return rcpp_result_gen;
END_RCPP
}
// graycode
IntegerMatrix graycode(unsigned int varying, unsigned int fixed);
RcppExport SEXP _blma_graycode(SEXP varyingSEXP, SEXP fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type varying(varyingSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type fixed(fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(graycode(varying, fixed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_blma_cva", (DL_FUNC) &_blma_cva, 7},
    {"_blma_blma", (DL_FUNC) &_blma_blma, 8},
    {"_blma_blma_fixed", (DL_FUNC) &_blma_blma_fixed, 9},
    {"_blma_graycode", (DL_FUNC) &_blma_graycode, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_blma(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
