# plot_variable_inclusion_graphs.R

# USCrime
USCrime_vw1 <- read.csv(header = FALSE, file = "USCrime_vw1.csv")
USCrime_vw2 <- read.csv(header = FALSE, file = "USCrime_vw2.csv")
USCrime_pip_AIC <- read.csv(header = FALSE, file = "USCrime_pip_AIC.csv")
USCrime_pip_BIC <- read.csv(header = FALSE, file = "USCrime_pip_BIC.csv")
pdf("USCrime_variable_selection.pdf")
par(mfrow = c(2, 2))
barplot(as.vector(as.matrix(USCrime_vw1)))
title("Exact Bayesian")
barplot(as.vector(as.matrix(USCrime_vw2)))
title("Approximate")
barplot(as.vector(as.matrix(USCrime_pip_AIC)))
title("AIC")
barplot(as.vector(as.matrix(USCrime_pip_BIC)))
title("BIC")
par(mfrow = c(1, 1))
dev.off()

# Hitters
Hitters_vw1 <- read.csv(header = FALSE, file = "Hitters_vw1.csv")
Hitters_vw2 <- read.csv(header = FALSE, file = "Hitters_vw2.csv")
Hitters_pip_AIC <- read.csv(header = FALSE, file = "Hitters_pip_AIC.csv")
Hitters_pip_BIC <- read.csv(header = FALSE, file = "Hitters_pip_BIC.csv")
pdf("Hitters_variable_selection.pdf")
par(mfrow = c(2, 2))
barplot(as.vector(as.matrix(Hitters_vw1)))
title("Exact Bayesian")
barplot(as.vector(as.matrix(Hitters_vw2)))
title("Approximate")
barplot(as.vector(as.matrix(Hitters_pip_AIC)))
title("AIC")
barplot(as.vector(as.matrix(Hitters_pip_BIC)))
title("BIC")
par(mfrow = c(1, 1))
dev.off()

# GradRate
GradRate_vw1 <- read.csv(header = FALSE, file = "GradRate_vw1.csv")
GradRate_vw2 <- read.csv(header = FALSE, file = "GradRate_vw2.csv")
GradRate_pip_AIC <- read.csv(header = FALSE, file = "GradRate_pip_AIC.csv")
GradRate_pip_BIC <- read.csv(header = FALSE, file = "GradRate_pip_BIC.csv")
pdf("GradRate_variable_selection.pdf")
par(mfrow = c(2, 2))
barplot(as.vector(as.matrix(GradRate_vw1)))
title("Exact Bayesian")
barplot(as.vector(as.matrix(GradRate_vw2)))
title("Approximate")
barplot(as.vector(as.matrix(GradRate_pip_AIC)))
title("AIC")
barplot(as.vector(as.matrix(GradRate_pip_BIC)))
title("BIC")
par(mfrow = c(1, 1))
dev.off()

# bodyfat
bodyfat_vw1 <- read.csv(header = FALSE, file = "bodyfat_vw1.csv")
bodyfat_vw2 <- read.csv(header = FALSE, file = "bodyfat_vw2.csv")
bodyfat_pip_AIC <- read.csv(header = FALSE, file = "bodyfat_pip_AIC.csv")
bodyfat_pip_BIC <- read.csv(header = FALSE, file = "bodyfat_pip_BIC.csv")
pdf("bodyfat_variable_selection.pdf")
par(mfrow = c(2, 2))
barplot(as.vector(as.matrix(bodyfat_vw1)))
title("Exact Bayesian")
barplot(as.vector(as.matrix(bodyfat_vw2)))
title("Approximate")
barplot(as.vector(as.matrix(bodyfat_pip_AIC)))
title("AIC")
barplot(as.vector(as.matrix(bodyfat_pip_BIC)))
title("BIC")
par(mfrow = c(1, 1))
dev.off()

# Wage
Wage_vw1 <- read.csv(header = FALSE, file = "Wage_vw1.csv")
Wage_vw2 <- read.csv(header = FALSE, file = "Wage_vw2.csv")
Wage_pip_AIC <- read.csv(header = FALSE, file = "Wage_pip_AIC.csv")
Wage_pip_BIC <- read.csv(header = FALSE, file = "Wage_pip_BIC.csv")
pdf("Wage_variable_selection.pdf")
par(mfrow = c(2, 2))
barplot(as.vector(as.matrix(Wage_vw1)))
title("Exact Bayesian")
barplot(as.vector(as.matrix(Wage_vw2)))
title("Approximate")
barplot(as.vector(as.matrix(Wage_pip_AIC)))
title("AIC")
barplot(as.vector(as.matrix(Wage_pip_BIC)))
title("BIC")
par(mfrow = c(1, 1))
dev.off()
