# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
#' @useDynLib taug
NULL

#' Calculate tau_g
#'
#' @param n The number of samples
#' @param mGraycode The graycode matrix
#' @param vR2 The vector of correlations
#' @param vlog_ZE The vector of log(ZE)
#' @export
rcpp_taug <- function(n, mGraycode, vR2, vlog_ZE) {
    .Call('taug_rcpp_taug', PACKAGE = 'taug', n, mGraycode, vR2, vlog_ZE)
}

#' Calculate tau_g from n, p and R2
#'
#' @param n The number of observations
#' @param p The number of parameters
#' @param R2 The correlation co-efficient
#' @return The log-lower bound of tau_g
#'
#' @export
tau_g <- function(n, p, R2) {
    .Call('taug_tau_g', PACKAGE = 'taug', n, p, R2)
}

