# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
#' @useDynLib taug
NULL

#' Calculate tau_g
#'
#' @param n The number of samples
#' @param mGraycode The graycode matrix
#' @param vR2 The vector of correlations
#' @param vlog_ZE The vector of log(ZE)
#' @export
taug <- function(n, mGraycode, vR2, vlog_ZE) {
    .Call('taug_taug', PACKAGE = 'taug', n, mGraycode, vR2, vlog_ZE)
}

#' Calculate the first integral for the posterior variance of beta_hat
#'
#' @param n The number of samples
#' @param p The number of covariates
#' @param R2 The correlation
#' @return The value of the integral
#' @export
E_g_one_plus_g <- function(n, p, R2) {
    .Call('taug_E_g_one_plus_g', PACKAGE = 'taug', n, p, R2)
}

#' Calculate the second integral for the posterior variance of beta_hat
#'
#' @param n The number of samples
#' @param p The number of covariates
#' @param R2 The correlation
#' @return The value of the integral
#' @export
E_g_one_plus_g_squared <- function(n, p, R2) {
    .Call('taug_E_g_one_plus_g_squared', PACKAGE = 'taug', n, p, R2)
}

#' Calculate posterior variance integrals based on vectors of n, p and R2 values
#'
#' @param vn A numeric vector of n values
#' @param vp A numeric vector of p values
#' @param vR2 A numeric value of
#' @return List of the values of the posterior variance integrals. E_g_one_plus_g contains the result of the first
#' integral, while E_g_one_plus_g_squared contains the second.
#' @export
g_ints <- function(vn, vp, vR2) {
    .Call('taug_g_ints', PACKAGE = 'taug', vn, vp, vR2)
}

#' Variance of g over one plug g under q
#' @param n The number of observations
#' @param p The number of covariates
#' @param R2 The correlation co-efficient, squared
#' @return The variance of g/(1+g) under q
#' @export
var_g_over_one_plus_g <- function(n, p, R2) {
    .Call('taug_var_g_over_one_plus_g', PACKAGE = 'taug', n, p, R2)
}

#' Calculate tau_g from n, p and R2
#'
#' @param n The number of observations
#' @param p The number of parameters
#' @param R2 The correlation co-efficient
#' @return The log-lower bound of tau_g
#'
#' @export
tau_g <- function(n, p, R2) {
    .Call('taug_tau_g', PACKAGE = 'taug', n, p, R2)
}

#' Calculate marginal log-likelihood log p(y)
#'
#' @param n The number of observations
#' @param p The number of covariates
#' @param R2 The correlation co-efficient, squared
#' @return The value of the marginal log-likelihood log p(y)
#' @export
log_p <- function(n, p, R2) {
    .Call('taug_log_p', PACKAGE = 'taug', n, p, R2)
}

#' Calculate AIC
#'
#' @param n The number of observations
#' @param p The number of covariates
#' @param R2 The correlation co-efficient, squared
#' @return The value of the marginal log-likelihood log p(y)
#' @export
aic <- function(n, p, R2) {
    .Call('taug_aic', PACKAGE = 'taug', n, p, R2)
}

#' Calculate BIC
#'
#' @param n The number of observations
#' @param p The number of covariates
#' @param R2 The correlation co-efficient, squared
#' @return The value of the marginal log-likelihood log p(y)
#' @export
bic <- function(n, p, R2) {
    .Call('taug_bic', PACKAGE = 'taug', n, p, R2)
}

#' Calculate the variational lower bound
#'
#' @param n The number of observations
#' @param p The number of covariates
#' @param c The variational parameter c
#' @param s The variational parameter s
#' @param tau_g The variational parameter tau_g
#' @param log_det_XTX The log of the determinant of X^T X
#' @param log_det_mSigma The log of the determinant of mSigma
#' @return The variational lower bound
#' @export
elbo <- function(n, p, c, s, tau_g, log_det_XTX, log_det_mSigma) {
    .Call('taug_elbo', PACKAGE = 'taug', n, p, c, s, tau_g, log_det_XTX, log_det_mSigma)
}

#' Calculate the exact precision
#'
#' @param n The number of observations
#' @param p The number of covariates
#' @param R2 The correlation coefficient squared
#' @return The exact precision
#' @export
exact_precision <- function(n, p, R2) {
    .Call('taug_exact_precision', PACKAGE = 'taug', n, p, R2)
}

#' Calculate the exact posterior expectation of g
#'
#' @param n The number of observations
#' @param p The number of covariates
#' @param R2 The correlation coefficient squared
#' @return The exact posterior expectation of g
#' @export
E_g_y <- function(n, p, R2) {
    .Call('taug_E_g_y', PACKAGE = 'taug', n, p, R2)
}

#' Calculate the approximate posterior expectation of g
#'
#' @param n The number of observations
#' @param p The number of covariates
#' @param R2 The correlation coefficient squared
#' @param c The co-efficient c of the exponential function exp(-c/g)
#' @return The approximate posterior expectation of g
#' @export
E_q_g_c <- function(n, p, R2, c) {
    .Call('taug_E_q_g_c', PACKAGE = 'taug', n, p, R2, c)
}

#' p_sigma2_y
#'
#' @param n The number of observations
#' @param p The number of covariates
#' @param R2 The correlation co-efficient, squared
#' @param sigma2 The value of sigma2
#' @return The value of p_sigma2_y
#' @export
p_sigma2_y <- function(n, p, R2, sigma2) {
    .Call('taug_p_sigma2_y', PACKAGE = 'taug', n, p, R2, sigma2)
}

#' q_sigma2
#'
#' @param r The first parameter of the Inverse Gamma distribution
#' @param s The second parameter of the Inverse Gamma distribution
#' @param sigma2 The value of sigma2
#' @return The value of q_sigma2
#' @export
q_sigma2 <- function(r, s, sigma2) {
    .Call('taug_q_sigma2', PACKAGE = 'taug', r, s, sigma2)
}

#' Calculate the accuracy of the approximation of sigma2
#'
#' @param n The number of observations
#' @param p The number of covariates
#' @param R2 The correlation co-efficient, squared
#' @param r The first parameter of the q(sigma2) distribution
#' @param s The second parameter of the q(sigma2) distribution
#' @return The accuracy of the approximation of sigma2
#' @export
accuracy_sigma2 <- function(n, p, R2, r, s) {
    .Call('taug_accuracy_sigma2', PACKAGE = 'taug', n, p, R2, r, s)
}

#' Calculate the accuracy of the approximation of g
#'
#' @param n The number of observations
#' @param p The number of covariates
#' @param R2 The correlation co-efficient, squared
#' @param c The c parameter
#' @return The accuracy of the approximation of g
#' @export
accuracy_g <- function(n, p, R2, c) {
    .Call('taug_accuracy_g', PACKAGE = 'taug', n, p, R2, c)
}

