# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
#' @useDynLib taug
NULL

#' Calculate tau_g
#'
#' @param n The number of samples
#' @param mGraycode The graycode matrix
#' @param vR2 The vector of correlations
#' @param vlog_ZE The vector of log(ZE)
#' @export
taug <- function(n, mGraycode, vR2, vlog_ZE) {
    .Call('taug_taug', PACKAGE = 'taug', n, mGraycode, vR2, vlog_ZE)
}

#' Calculate the first integral for the posterior variance of beta_hat
#'
#' @param n The number of samples
#' @param p The number of covariates
#' @param R2 The correlation
#' @return The value of the integral
#' @export
E_g_one_plus_g <- function(n, p, R2) {
    .Call('taug_E_g_one_plus_g', PACKAGE = 'taug', n, p, R2)
}

#' Calculate the second integral for the posterior variance of beta_hat
#'
#' @param n The number of samples
#' @param p The number of covariates
#' @param R2 The correlation
#' @return The value of the integral
#' @export
E_g_one_plus_g_squared <- function(n, p, R2) {
    .Call('taug_E_g_one_plus_g_squared', PACKAGE = 'taug', n, p, R2)
}

#' Calculate posterior variance integrals based on vectors of n, p and R2 values
#'
#' @param vn A numeric vector of n values
#' @param vp A numeric vector of p values
#' @param vR2 A numeric value of
#' @return List of the values of the posterior variance integrals. E_g_one_plus_g contains the result of the first
#' integral, while E_g_one_plus_g_squared contains the second.
#' @export
g_ints <- function(vn, vp, vR2) {
    .Call('taug_g_ints', PACKAGE = 'taug', vn, vp, vR2)
}

#' Calculate tau_g from n, p and R2
#'
#' @param n The number of observations
#' @param p The number of parameters
#' @param R2 The correlation co-efficient
#' @return The log-lower bound of tau_g
#'
#' @export
tau_g <- function(n, p, R2) {
    .Call('taug_tau_g', PACKAGE = 'taug', n, p, R2)
}

#' Calculate variance of tau_g from n, p and R2
#'
#' @param n The number of observations
#' @param p The number of parameters
#' @param R2 The correlation co-efficient
#' @return The log-lower bound of tau_g
#'
#' @export
var_g_over_one_plus_g <- function(n, p, R2) {
    .Call('taug_var_g_over_one_plus_g', PACKAGE = 'taug', n, p, R2)
}

#' Calculate marginal log-likelihood log p(y)
#'
#' @param n The number of observations
#' @param p The number of covariates
#' @param R2 The correlation co-efficient, squared
#' @return The value of the marginal log-likelihood log p(y)
#' @export
log_p <- function(n, p, R2) {
    .Call('taug_log_p', PACKAGE = 'taug', n, p, R2)
}

#' Calculate the variational lower bound
#'
#' @param n The number of observations
#' @param p The number of covariates
#' @param c The variational parameter c
#' @param s The variational parameter s
#' @param tau_g The variational parameter tau_g
#' @param log_det_XTX The log of the determinant of X^T X
#' @param log_det_mSigma The log of the determinant of mSigma
#' @return The variational lower bound
#' @export
elbo <- function(n, p, c, s, tau_g, log_det_XTX, log_det_mSigma) {
    .Call('taug_elbo', PACKAGE = 'taug', n, p, c, s, tau_g, log_det_XTX, log_det_mSigma)
}

