// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_all_correlations_mX
NumericVector rcpp_all_correlations_mX(NumericVector vy, NumericMatrix mX, int intercept_col, bool bIntercept, bool bCentre);
RcppExport SEXP correlation_rcpp_all_correlations_mX(SEXP vySEXP, SEXP mXSEXP, SEXP intercept_colSEXP, SEXP bInterceptSEXP, SEXP bCentreSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type vy(vySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< int >::type intercept_col(intercept_colSEXP);
    Rcpp::traits::input_parameter< bool >::type bIntercept(bInterceptSEXP);
    Rcpp::traits::input_parameter< bool >::type bCentre(bCentreSEXP);
    __result = Rcpp::wrap(rcpp_all_correlations_mX(vy, mX, intercept_col, bIntercept, bCentre));
    return __result;
END_RCPP
}
// rcpp_all_correlations_mX_mZ
NumericVector rcpp_all_correlations_mX_mZ(NumericVector vy, NumericMatrix mX, NumericMatrix mZ, int intercept_col, bool bIntercept, bool bCentre);
RcppExport SEXP correlation_rcpp_all_correlations_mX_mZ(SEXP vySEXP, SEXP mXSEXP, SEXP mZSEXP, SEXP intercept_colSEXP, SEXP bInterceptSEXP, SEXP bCentreSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type vy(vySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mZ(mZSEXP);
    Rcpp::traits::input_parameter< int >::type intercept_col(intercept_colSEXP);
    Rcpp::traits::input_parameter< bool >::type bIntercept(bInterceptSEXP);
    Rcpp::traits::input_parameter< bool >::type bCentre(bCentreSEXP);
    __result = Rcpp::wrap(rcpp_all_correlations_mX_mZ(vy, mX, mZ, intercept_col, bIntercept, bCentre));
    return __result;
END_RCPP
}
