# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_all_correlations_mX <- function(vy, mX, intercept_col, bIntercept, bCentre) {
    .Call('correlation_rcpp_all_correlations_mX', PACKAGE = 'correlation', vy, mX, intercept_col, bIntercept, bCentre)
}

rcpp_all_correlations_mX_mZ <- function(vy, mX, mZ, intercept_col, bIntercept, bCentre) {
    .Call('correlation_rcpp_all_correlations_mX_mZ', PACKAGE = 'correlation', vy, mX, mZ, intercept_col, bIntercept, bCentre)
}

