# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run a Collapsed Variational Approximation to find the K best linear models
#'
#' @param gamma_initial Matrix of initial models, a K by p logical matrix
#' @param vy Vector of responses
#' @param mX Matrix of covariates
#' @param K The number of particles in the population
#' @param lambda The weighting factor for the entropy in f_lambda. Defaults to 1.
#' @param log_lik The log likelihood function to use in ranking models. One of
#' 							 "log_prob1" "BIC" "ZE" "3" "4" "5" "6" "7".
#' @param bUnique Whether to ensure uniqueness in the population of particles or not. Defaults to true.
#' @return A list containing the named element models, which is a K by p matrix of the models
#'					selected by the algorithm, and the named element trajectory, which includes a list
#'					of the populations of models for each iteration of the algorithm until it converged
#' @export
cva <- function(gamma_initial, vy_in, mX_in, K, lambda = 1., log_lik = "maruyama", bUnique = TRUE) {
    .Call('_correlation_cva', PACKAGE = 'correlation', gamma_initial, vy_in, mX_in, K, lambda, log_lik, bUnique)
}

#' @importFrom Rcpp evalCpp
#' @useDynLib correlation
NULL

#' Calculate the correlation of all the sub-models of mX and vy
#'
#' @param vy Vector of responses
#' @param mX Covariate matrix
#' @param g_prior The g-prior to use. The choices of g-prior available are "maruyama", "BIC", "ZE",
#' "liang_g1", "liang_g2", "liang_g3", "robust_bayarri1" and "robust_bayarri2"
#' @param intercept_col The index of the column in mX containing the intercept, if any
#' @param bNatural_Order Whether to return the results in natural order or graycode order. Defaults to graycode order.
#' @param bIntercept Logical value indicating whether there is an intercept column or not
#' @param bCentre Logical value indicating whether to centre the response vector and covariance matrix or not
#' @param cores The number of cores to use
#' @return A list containing 
#' vR2, the vector of correlations for each model
#' vp_gamma, the vector of number of covariates for each model
#' vlogp, the vector of logs of the likelihoods of each model
#' vinclusion_prob, the vector of inclusion probabilities for each of the covariates
#' @export
all_correlations_mX <- function(vy, mX, g_prior, intercept_col = 1L, bNatural_Order = FALSE, bIntercept = FALSE, bCentre = FALSE, cores = 1L) {
    .Call('_correlation_all_correlations_mX', PACKAGE = 'correlation', vy, mX, g_prior, intercept_col, bNatural_Order, bIntercept, bCentre, cores)
}

#' Calculate the correlation of all the sub-models mX/mZ and vy, where mX is fixed in every model and the sub-models of mZ are included
#'
#' @param vy Vector of responses
#' @param mX Fixed covariate matrix
#' @param mZ Varying covariate matrix
#' @param g_prior The g-prior to use. The choices of g-prior available are "maruyama", "BIC", "ZE",
#' "liang_g1", "liang_g2", "liang_g3", "robust_bayarri1" and "robust_bayarri2"
#' @param intercept_col The index of the column in mX containing the intercept, if any
#' @param bNatural_Order Whether to return the results in natural order or graycode order. Defaults to graycode order.
#' @param bIntercept Logical value indicating whether there is an intercept column or not
#' @param bCentre Logical value indicating whether to centre the response vector and covariance matrix or not
#' @param cores The number of cores to use
#' @return A list containing 
#' vR2, the vector of correlations for each model
#' vp_gamma, the vector of number of covariates for each model
#' vlogp, the vector of logs of the likelihoods of each model
#' vinclusion_prob, the vector of inclusion probabilities for each of the covariates
#' @export
all_correlations_mX_mZ <- function(vy, mX, mZ, g_prior, intercept_col = 1L, bNatural_Order = FALSE, bIntercept = FALSE, bCentre = FALSE, cores = 1L) {
    .Call('_correlation_all_correlations_mX_mZ', PACKAGE = 'correlation', vy, mX, mZ, g_prior, intercept_col, bNatural_Order, bIntercept, bCentre, cores)
}

#' Return the graycode matrix
#'
#' @param varying The number of covariates varying in the graycode matrix
#' @param fixed The number of fixed covariates in the graycode matrix. These covariates will always be included
#' @return The graycode matrix. The number of fixed columns will be included in the lower indexed columns
#' as 1s, while the higher indexed columns will varying depending on whether each covariate in the varying
#' set of covariates is included or not.
#' @export
graycode <- function(varying, fixed = 0L) {
    .Call('_correlation_graycode', PACKAGE = 'correlation', varying, fixed)
}

