# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastdiag <- function(lambda, C) {
    .Call('_zipvb_fastdiag', PACKAGE = 'zipvb', lambda, C)
}

fastdiag2 <- function(R, C) {
    .Call('_zipvb_fastdiag2', PACKAGE = 'zipvb', R, C)
}

fastsolve <- function(R, C) {
    .Call('_zipvb_fastsolve', PACKAGE = 'zipvb', R, C)
}

