// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// taug
List taug(unsigned int n, NumericMatrix mGraycode, NumericVector vR2, NumericVector vlog_ZE);
RcppExport SEXP taug_taug(SEXP nSEXP, SEXP mGraycodeSEXP, SEXP vR2SEXP, SEXP vlog_ZESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mGraycode(mGraycodeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vR2(vR2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vlog_ZE(vlog_ZESEXP);
    rcpp_result_gen = Rcpp::wrap(taug(n, mGraycode, vR2, vlog_ZE));
    return rcpp_result_gen;
END_RCPP
}
// E_g_one_plus_g
double E_g_one_plus_g(int n, double p, double R2);
RcppExport SEXP taug_E_g_one_plus_g(SEXP nSEXP, SEXP pSEXP, SEXP R2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type R2(R2SEXP);
    rcpp_result_gen = Rcpp::wrap(E_g_one_plus_g(n, p, R2));
    return rcpp_result_gen;
END_RCPP
}
// E_g_one_plus_g_squared
double E_g_one_plus_g_squared(int n, int p, double R2);
RcppExport SEXP taug_E_g_one_plus_g_squared(SEXP nSEXP, SEXP pSEXP, SEXP R2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type R2(R2SEXP);
    rcpp_result_gen = Rcpp::wrap(E_g_one_plus_g_squared(n, p, R2));
    return rcpp_result_gen;
END_RCPP
}
// g_ints
List g_ints(NumericVector vn, NumericVector vp, NumericVector vR2);
RcppExport SEXP taug_g_ints(SEXP vnSEXP, SEXP vpSEXP, SEXP vR2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vn(vnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vp(vpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vR2(vR2SEXP);
    rcpp_result_gen = Rcpp::wrap(g_ints(vn, vp, vR2));
    return rcpp_result_gen;
END_RCPP
}
// var_g_over_one_plus_g
double var_g_over_one_plus_g(int n, int p, double R2);
RcppExport SEXP taug_var_g_over_one_plus_g(SEXP nSEXP, SEXP pSEXP, SEXP R2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type R2(R2SEXP);
    rcpp_result_gen = Rcpp::wrap(var_g_over_one_plus_g(n, p, R2));
    return rcpp_result_gen;
END_RCPP
}
// tau_g
double tau_g(int n, int p, double R2);
RcppExport SEXP taug_tau_g(SEXP nSEXP, SEXP pSEXP, SEXP R2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type R2(R2SEXP);
    rcpp_result_gen = Rcpp::wrap(tau_g(n, p, R2));
    return rcpp_result_gen;
END_RCPP
}
// log_p
double log_p(int n, int p, double R2);
RcppExport SEXP taug_log_p(SEXP nSEXP, SEXP pSEXP, SEXP R2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type R2(R2SEXP);
    rcpp_result_gen = Rcpp::wrap(log_p(n, p, R2));
    return rcpp_result_gen;
END_RCPP
}
// aic
double aic(int n, int p, double R2);
RcppExport SEXP taug_aic(SEXP nSEXP, SEXP pSEXP, SEXP R2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type R2(R2SEXP);
    rcpp_result_gen = Rcpp::wrap(aic(n, p, R2));
    return rcpp_result_gen;
END_RCPP
}
// bic
double bic(int n, int p, double R2);
RcppExport SEXP taug_bic(SEXP nSEXP, SEXP pSEXP, SEXP R2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type R2(R2SEXP);
    rcpp_result_gen = Rcpp::wrap(bic(n, p, R2));
    return rcpp_result_gen;
END_RCPP
}
// elbo
double elbo(int n, int p, double c, double s, double tau_g, double log_det_XTX, double log_det_mSigma);
RcppExport SEXP taug_elbo(SEXP nSEXP, SEXP pSEXP, SEXP cSEXP, SEXP sSEXP, SEXP tau_gSEXP, SEXP log_det_XTXSEXP, SEXP log_det_mSigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type tau_g(tau_gSEXP);
    Rcpp::traits::input_parameter< double >::type log_det_XTX(log_det_XTXSEXP);
    Rcpp::traits::input_parameter< double >::type log_det_mSigma(log_det_mSigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(elbo(n, p, c, s, tau_g, log_det_XTX, log_det_mSigma));
    return rcpp_result_gen;
END_RCPP
}
