// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_taug
List rcpp_taug(unsigned int n, NumericMatrix mGraycode, NumericVector vR2, NumericVector vlog_ZE);
RcppExport SEXP taug_rcpp_taug(SEXP nSEXP, SEXP mGraycodeSEXP, SEXP vR2SEXP, SEXP vlog_ZESEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mGraycode(mGraycodeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vR2(vR2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vlog_ZE(vlog_ZESEXP);
    __result = Rcpp::wrap(rcpp_taug(n, mGraycode, vR2, vlog_ZE));
    return __result;
END_RCPP
}
